# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
            ],
        ),
    ]
