# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('bus_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_board.BusOrganisation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_board.Route')),
            ],
        ),
    ]
