# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0005_schedule_price'),
        ('bus_board', '0005_ticket'),
    ]

    operations = [
    ]
