# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0006_merge_20180118_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['price']},
        ),
    ]
