# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0007_auto_20180119_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
