# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0008_auto_20180122_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_code', models.CharField(max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_board.Schedule')),
            ],
        ),
    ]
