# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_board', '0007_auto_20180119_0747'),
        ('bus_board', '0009_ticket'),
    ]

    operations = [
    ]
